# Generated by Django 4.2.21 on 2025-05-18 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='姓名')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('sex', models.IntegerField(blank=True, choices=[(2, '女'), (1, '男')], null=True, verbose_name='性别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.classes', verbose_name='班级')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
