# Generated by Django 4.2.21 on 2025-05-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_students_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
    ]
