# Generated by Django 4.2.21 on 2025-05-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_students_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app1.classes', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(2, '女'), (1, '男')], null=True, verbose_name='性别'),
        ),
    ]
